### ISSUE TITLE
Does setup-lazarus action use cache?

### ISSUE THREAD

**Issue by pashagolub** [gcarreno/setup-lazarus#13]
Hello,

thanks a lot for your work! It's not an issue, rather the question. Does `setup-lazarus` action use GHA caching functionality or binaries are installed/downloaded from scratch every time?

Regards

**Comment by gcarreno** [comment]
Hey Pavlo(@pashagolub),

Really sorry to have taken so much time to answer to this, my mind has been else where for quite a while :)

I can say that it downloads the packages every time.
I'm very new at all this TypeScript and GH Actions and so much of the coding is done by feeling in the dark.

I would appreciate if you could point me to something that would explain how I could cache the packages, cuz that makes a lot more sense!!

Cheers,
Gus

**Comment by pashagolub** [comment]
oh, I forgot about this issue as well :-) so no problem.

I'll get back to this later when I'll be working on GHA closely.

Thanks

**Comment by gcarreno** [comment]
Hey Pavlo(@pashagolub),

I've looked at some other actions that use cached content and I'm in the middle of getting this sorted.

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Pavlo(@pashagolub),

Finally implemented it with release v3.1

Cheers,
Gus

**Comment by pashagolub** [comment]
Thanks! Works like a charm!
