### ISSUE TITLE
Linker errors on FPC 3.0.4 under ubuntu-latest (22.04)

### ISSUE THREAD

**Issue by alex65536** [gcarreno/setup-lazarus#25]
Under Lazarus 1.8.4 and 2.0.8 (and probably others), the error is as follows:

```
/usr/bin/ld: /usr/lib/fpc/3.0.4/units/x86_64-linux/rtl/cprt0.o: in function `_start':
(.text+0x3c): undefined reference to `__libc_csu_init'
/usr/bin/ld: (.text+0x43): undefined reference to `__libc_csu_fini'
Error: (9013) Error while linking
Fatal: (10026) There were 1 errors compiling module, stopping
Fatal: (1018) Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode
```

Lazarus version based on FPC 3.2.0 (from 2.0.10) build successfully.

The build was also successful on Lazarus 2.0.8 before `ubuntu-latest` has changed from 20.04 to 22.04.

Please take a look :)

**Comment by gcarreno** [comment]
Hey Alex(@alex65536),

Unfortunately this is an issue I cannot solve.

This is directly related to the versions of Free Pascal and Lazarus.

This tool only downloads the Source Forge install binaries and then installs them.
Anything related to what the install binaries contain and any issues with mismatched version pairs cannot be resolved via `setup-lazarus`. You'll have to discuss this on the GitLab issue section of FPC or Lazarus.

I'm really, really sorry I can't help you more on this.

Cheers,
Gus
