### ISSUE TITLE
Upgrade Node 16 -> Node 20

### ISSUE THREAD

**Issue by michaliskambi** [gcarreno/setup-lazarus#29]
The action uses node16 right now ( https://github.com/gcarreno/setup-lazarus/blob/master/action.yml#L23 ). 

GitHub suggests to transition all actions to Node 20, see https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/ . 

Running workflows using the current action, for now, works perfectly, but we get a warning about it:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: gcarreno/setup-lazarus@v3.2.17. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Note that GitHub also recently announced more information about Node 16 -> 20 on https://github.blog/changelog/2024-05-17-updated-dates-for-actions-runner-using-node20-instead-of-node16-by-default/ , though from what I understand that news concerns more people using Node in the GH-hosted runners, not actions' authors.

I'm not aware of any real problem with using Node 16, as said above -- everything seems to work perfectly, we only get a warning from the workflow that can be just ignored. That being said, at some point I guess this will be more forced, so I'm submitting an issue -- maybe you'd like to address this earlier :) If you will have a new version of the action using Node 20, I will be happy to test, switching my workflows to use it ( https://github.com/castle-engine/castle-engine/ , https://github.com/pasdoc/pasdoc/ ) and report if everything works OK.

**Comment by vmaskmovps** [comment]
As of yesterday, we're on Node 20: https://github.com/gcarreno/setup-lazarus/commit/5979e7da1cf2d98e2094084415e04d7a132faa5a
