### ISSUE TITLE
Add support for Lazarus 3.2 and 3.4

### ISSUE THREAD

**Issue by michaliskambi** [gcarreno/setup-lazarus#30]
From what I can see, the latest stable Lazarus one can request using https://github.com/gcarreno/setup-lazarus is 3.0.

Please add support for 3.2 and (newly released  -- https://forum.lazarus.freepascal.org/index.php/topic,67439.0.html ) 3.4. 

Thank you!

**Comment by vmaskmovps** [comment]
I am working on a full rewrite that will also add support for 3.x and prepare for 4.0-RC1 (and 4.0 when it will eventually be released). @gcarreno left me to manage this repo and he didn't see your issue, so sorry about that.

**Comment by michaliskambi** [comment]
> I am working on a full rewrite that will also add support for 3.x and prepare for 4.0-RC1 (and 4.0 when it will eventually be released). @gcarreno left me to manage this repo and he didn't see your issue, so sorry about that.

Thank you very much, good to see the development is active! I'll switch to the new action version 3.3.0 that I see you just released ( https://github.com/gcarreno/setup-lazarus/releases ), and switch to new Lazarus versions in workflows using this, and test it on Castle Game Engine repos.
